routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController')->name('/');

Route::get('local/{lang}','LocalController')->name('local');
Route::get('checkout','CheckoutController@show')->name('show.checkout');
Route::post('checkout/update','CheckoutController@update')->name('update.checkout');

Route::post('setProduct','CheckoutController@setProduct')->name('set.checkout');

Route::resource('cart','CartController');

Route::resource('order','OrderController');

Route::any('callback','OrderController@callback')->name('call_back');

Route::post('coupon','CouponController')->name('coupon');

Route::get('cities','CityController')->name('cities');
Route::post('calcShipping','CalcShippingController@index')->name('calcShipping');
Route::view('success','success')->name('success');
Route::view('product','product');

Route::get('bound','BoundController')->name('bound');
Route::get('page/{slug}','PageController')->name('page');

Route::get('before-and-after','BeforeAndAfterController')->name('before_after');



Route::group(['prefix' => 'admin'], function () {
    Route::post('shipping_request','ShippingController@index')->name('shipping.request');
    Route::post('print_invoices','InvoiceController')->name('print_invoices');
    Voyager::routes();
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{

    protected $table = 'orders';
    public $timestamps = true;
    protected $fillable = array('invoice_number', 'payment_invoice','tracking_code', 'name', 'phone', 'email', 'zone', 'city', 'postcode', 'address', 'notes', 'sub_total', 'coupon', 'coupon_price', 'shipping', 'total', 'payment_method', 'shipping_method', 'order_status_id');

    public function orderProducts() {
        return $this->hasMany(OrderProduct::class,'order_id');
    }

    public function scopeNotNull($query) {
        return $query->where('order_status','!=','NULL');
    }

    public function getFullAddressAttribute() {

        return $this->addressAttribute();
    }

    public function getAddressBrowseAttribute() {
        return $this->addressAttribute();
    }
    public function getAddressReadAttribute() {
        return $this->addressAttribute();
    }


    private function addressAttribute() {
        $address = json_decode($this->address);
        $new_address = "";
        if (!is_null($address)) {

            foreach ($address as $title=>$add) {
                $new_address .= $title . " : ". $add . "<br>";

            }


        } else {
            $new_address .= "Zone : ".$this->zone . "<br>";
            $new_address .= "City : ".$this->city . "<br>";
            $new_address .= "Address : ".$this->address . "<br>";
        }

        return $new_address;
    }

}

resources/views/before_after.blade.php
@extends('layouts.main')

@section('content')
    <div id="content" class="col-sm-12 item-article">
        <div class="so-page-builder">
            <div class="container page-builder-ltr">
                <div class="row row_e8kb  row-style ">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 col_8552  col-style">

                        <div class="module sohomepage-slider ">
                            <h3 class="modtitle" style="padding:20px 0;">{{trans('site.before_and_after')}}</h3>



                            <div class="modcontent">

                                <div id="sohomepage-slider1">
                                    <div class="popup-gallery" style="min-height: 80vh">

                                        @forelse ($images as $image)
                                            <a href="{{\Illuminate\Support\Facades\Storage::url($image->image)}}" title="Before And After"><img src="{{\Illuminate\Support\Facades\Storage::url($image->image)}}" width="200" height="200"></a>

                                            @empty

                                        @endforelse
                                    </div>
                                </div>
                            </div> <!--/.modcontent-->



                        </div>


                    </div>

                </div>
            </div>

        </div>

        <p><br></p>
    </div>
@endsection

@push('css')
    <link href="{{asset('css/magnific-popup.css')}}" rel="stylesheet">
@endpush

@push('js')
    <script src="{{asset('js/jquery.magnific-popup.min.js')}}"></script>

    <script defer>
        $(document).ready(function() {
            $('.popup-gallery').magnificPopup({
                delegate: 'a',
                type: 'image',
                // tLoading: 'Loading image #%curr%...',
                mainClass: 'mfp-img-mobile',
                gallery: {
                    enabled: true,
                    navigateByImgClick: true,
                    preload: [0,1] // Will preload 0 - before current, and 1 after the current image
                },

            });
        });
    </script>
@endpush

resources/views/checkout.blade.php
@extends('layouts.main')
@push('css')
    <link rel="stylesheet" href="{{asset('so_onepagecheckout.css')}}">
@endpush
@section('content')
    <form method="post" action="{{route('order.store')}}">
        @csrf
    <div class="col-sm-12">
        <div class="so-onepagecheckout layout1 ">
            <div class="col-left col-lg-6 col-md-6 col-sm-6 col-xs-12">




                <div class="checkout-content checkout-register">

                    <fieldset id="account">
                        <h2 class="secondary-title"><i class="fa fa-user-plus"></i>{{trans('site.personal_information')}}</h2>
                        <div class="payment-new box-inner">


                            <div class="form-group input-firstname required" style="width: 100%; float: left;">
                                <input type="text" name="name" value="{{old('name')}}" placeholder="{{trans('validation.attributes.name')}}" id="input-payment-firstname"
                                       class="form-control" required>
                            </div>


                            <div class="form-group required">
                                <input type="text" name="email" value="{{old('email')}}" placeholder="{{trans('validation.attributes.email')}}" id="input-payment-email"
                                       class="form-control" required>
                            </div>


                        </div>
                    </fieldset>

                    <fieldset id="address">

                        <h2 class="secondary-title"><i class="fa fa-map-marker"></i>{{trans('site.shipping_information')}}</h2>


                        <div class=" checkout-payment-form">

                            <div class="box-inner">
                                @include('component.loader')
                                    @if ($country_code->code == 'KW')
                                    <div class="form-group required">
                                        <input type="text" id="dial_code" value="{{$country_code->dial_code}}"
                                               disabled required class="text-center" style="width: 30%!important;border-right: 1px solid black;direction:ltr">
                                        <input type="text"  name="phone" value="{{old('phone')}}" placeholder="{{trans('validation.attributes.phone')}}"
                                               class="" style="width: 70%!important" required>


                                    </div>


                                        <!--area -->
                                    <div class="form-group required" >
                                        <input type="text" name="area"  value="{{old('area')}}" placeholder="{{trans('site.area')}}"
                                                class="form-control" required>
                                    </div>

                                        <!-- end area -->

                                            <!-- block  -->
                                            <div class="form-group required" >
                                                <input type="text" name="block" value="{{old('block')}}"  placeholder="{{trans('site.block')}}"
                                                       class="form-control" required>
                                            </div>
                                            <!-- end block -->

                                            <!--  street -->
                                            <div class="form-group required" >
                                                <input type="text" name="street" value="{{old('street')}}"  placeholder="{{trans('site.street')}}"
                                                       class="form-control" required>
                                            </div>
                                            <!--  end street -->

                                        <!-- house  -->
                                            <div class="form-group required" >
                                                <input type="text" name="house" value="{{old('house')}}" placeholder="{{trans('site.house')}}"
                                                       class="form-control" required>
                                            </div>
                                        <!-- end house -->
                                    @else
                                            <div class="form-group required" >
                                                    <select class="form-control" name="zone" id="zone" required>
                                                        <option selected disabled>{{trans('site.zone')}}</option>
                                                        @foreach($all_countries as $country)
                                                            <option value="{{$country->CountryCode}}"

                                                            >{{$country->CountryName}}</option>
                                                        @endforeach

                                                    </select>

                                            </div>

                                            <div class="form-group required" >
                                                <select class="form-control" name="city" id="city" required>
                                                    <option selected disabled>{{trans('validation.attributes.city')}}</option>
                                                </select>

                                            </div>

                                    <div class="form-group required">
                                        <input type="text" id="dial_code" value="+"
                                               disabled required class="text-center" style="width: 30%!important;border-right: 1px solid black;">
                                        <input type="text"  name="phone" value="{{old('phone')}}" placeholder="{{trans('validation.attributes.phone')}}"
                                               class="" style="width: 70%!important" required>


                                    </div>


                                    <!--area -->
                                            <div class="form-group required" >
                                                <input type="text" name="postcode"  value="{{old('postcode')}}" placeholder="{{trans('site.postcode')}}"
                                                       class="form-control" >
                                            </div>

                                            <!--area -->
                                            <div class="form-group required" >
                                                <input type="text" name="address"  value="{{old('address')}}" placeholder="{{trans('validation.attributes.address')}}"
                                                       class="form-control" required>
                                            </div>

                                        @endif

                            </div>
                        </div>


                    </fieldset>





                </div>

            </div>

            <div class="col-right col-lg-6 col-md-6 col-sm-6 col-xs-12">
                <section class="section-left">
                    @if (session()->get('country')->code == 'KW')
                    <div class="ship-payment">
                        <div class="checkout-content checkout-shipping-methods">

                            <h2 class="secondary-title"><i class="fa fa-location-arrow"></i>
                                {{trans('site.payment_method')}}
                            </h2>
                            <div class="box-inner">
                                <div class="form-group">
                                    <input type="radio" name="payment_method"  value="CASH ON DELIVERY"
                                           checked>
                                    <span><strong>{{trans('site.CASH_ON_DELIVERY')}}</strong></span>


                                </div>

                                <div class="form-group">
                                    <input type="radio"  name="payment_method" value="Credit Card"
                                           >
                                    <span><strong>{{trans('site.knet_visa')}}</strong></span>


                                </div>


                            </div>
                        </div>





                    </div>
                    @endif


                </section>
                <section class="section-right">
                    <div id="coupon_voucher_reward">
                        <div class="checkout-content coupon-voucher">
                            <h2 class="secondary-title"><i class="fa fa-gift"></i>{{trans('site.coupon')}}</h2>
                            <div class="box-inner">
                                <div class="panel-body checkout-coupon">
                                    <label class="col-sm-2 control-label" for="input-coupon">{{trans('site.coupon')}}</label>
                                    <div class="input-group">
                                        <input type="text"  value="{{old('coupon') ?? session()->get('coupon')}}" placeholder="{{trans('site.coupon')}}" id="input-coupon"
                                               class="form-control">
                                        <span class="input-group-btn">
                                    <input type="button"  id="button-coupon"

                                           value="{{trans('site.apply_coupon')}}"
                                           class="btn-primary button">
                                </span>
                                    </div>
                                </div>



                            </div>
                        </div>

                    </div>
                    <div id="payment">
                        @include('component.loader')
                        <div id="totals">
                            {!! $totals !!}
                        </div>
                    </div>







                    <div class="checkout-content confirm-section">
                        <div>
                            <h2 class="secondary-title"><i class="fa fa-comment"></i>{{trans('site.notes')}}</h2>
                            <label>
                                <textarea name="notes" rows="8" class="form-control " value="{{old('notes')}}"></textarea>
                            </label>
                        </div>



                        <div class="confirm-order">
                            <button id="so-checkout-confirm-button"
                                    class="btn btn-primary button confirm-button">
                                {{trans('site.submit_order')}}
                            </button>
                        </div>
                    </div>
                </section>
            </div>
        </div>

    </div>
    </form>
@endsection

resources/views/home.blade.php
@extends('layouts.main')


@section('content')

        <div class="m-4 p-4">
            <div class="container">
                <div class="products_header d-flex justify-content-center align-items-center">
                    <h2 class="text-center">{{trans('site.products')}}</h2>
                </div>
                @forelse ($products as $product)
                <div class="product_body col-lg-4  col-md-6 col-sm-12 col-xs-12 ">
                    <!-- product card -->


                    <div class="row">

                            <div class="thumbnail col-sm-8">
                                <img  alt="{{$product->name}}"
                                     src="{{Storage::url($product->image_kw)}}"

                                     title=""/>

                                <div class="caption text-center">
                                    <h3>{{$product->translate()->name}} </h3>
                                    <h4><p>{{number_format($product->price,2)}} {{trans('site.k.d')}}</p> </h4>
                                    <p class="text-center">
                                        <button  class="btn btn-sm btn-success inc" data-id="{{$product->id}}">
                                            <i class="fa fa-plus"></i>
                                        </button>

                                        <input  id="product_{{$product->id}}" type="text" class="product_number text-center" placeholder="1" value="1"/>

                                        <button class="btn btn-sm btn-warning dec" data-id="{{$product->id}}">
                                            <i class="fa fa-minus"></i>
                                        </button>


                                    </p>
                                    <p class="text-center"><a href="#" v-on:click.prevent="add_to_cart({{$product->id}},true)"  class="btn btn-primary btn-sm buy_button" data-id="{{$product->id}}" role="button">{{trans('site.buy_now')}}</a>
                                        <a href="#" v-on:click.prevent="add_to_cart({{$product->id}})" class="btn btn-default btn-sm " role="button">{{trans('site.add_to_cart')}}</a></p>
                                </div>
                            </div>

                    </div>



                    <!-- end product cart -->
                </div>
                @empty

                    <h2 class="text-center">{{trans('site.no_products')}}</h2>

                @endforelse

            </div>

        </div>

@endsection

resources/views/invoice.blade.php
<!DOCTYPE html>

<html dir="rtl" lang="ar">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title>الفاتورة </title>


    <link href="{{asset('catalog/view/javascript/bootstrap/css/bootstrap.css')}}" rel="stylesheet" media="all">
    <script type="text/javascript" src="{{asset('catalog/view/javascript/jquery/jquery-2.1.1.min.js')}}"></script>
{{--    <script type="text/javascript" src="./الفاتورة رقم_files/bootstrap.min.js.download"></script>--}}

    <link type="text/css" href="{{asset('stylesheet.css')}}" rel="stylesheet" media="all">
</head>

<body>
<div class="container">
    @foreach($orders as $order)
    <div style="page-break-after: always;">
        <h1>الفاتورة رقم #{{$order->invoice_number}}</h1>
        <table class="table table-bordered">
            <thead>
            <tr>
                <td colspan="2">تفاصيل الطلب</td>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td style="width: 50%;">
                    <address>
                        <strong>{{setting('site.name')}}</strong><br>
                        Rimuathya<br>
                        Block 6<br>
                        St shaheen alghanim
                    </address>
                    <b>البريد الالكتروني:</b> admin@curlygirlskw.com<br>
                    <b>الموقع الالكتروني:</b> <a href="{{route('/')}}">{{route('/')}}</a>
                </td>
                <td style="width: 50%;"><b>تاريخ الاضافة
                        :{{$order->created_at->format('Y/m/d')}}
                    </b><br>
                    <b>رقم الطلب:</b> {{$order->id}}<br>
                    <b>طريقة الدفع:</b> {{$order->payment_method}}<br>
                    <b>طريقة الشحن:</b>{{$order->shipping_method}}<br>

                    <b>اسم العميل :{{$order->name}}</b>
                    <br>
                    <b>رقم هاتف العميل : {{$order->phone}}</b>
                </td>

            </tr>
            </tbody>
        </table>


        <table class="table table-bordered">
            <thead>
            <tr>

                <td style="width: 100%;"><b>العنوان</b></td>

            </tr>
            </thead>
            <tbody>
            <tr>

                <td>
                    <address>
                        {!! $order->full_address !!}
                    </address>
                </td>
            </tr>
            </tbody>
        </table>
        <table class="table table-bordered">
            <thead>
            <tr>
                <td><b>الطلبات</b></td>

                <td class="text-right"><b>الكمية</b></td>
                <td class="text-right"><b>سعر الوحدة</b></td>
                <td class="text-right"><b>الاجمالي</b></td>
            </tr>
            </thead>
            <tbody>

            @foreach ($order->orderProducts as $product)
            <tr>
                <td>{{$product->product->name}}
                </td>

                <td class="text-right">{{$product->quantity}}</td>
                <td class="text-right"> {{number_format($product->total,2)}} K.D</td>
                <td class="text-right"> K.D {{number_format($product->total * $product->quantity,2)}}</td>
            </tr>
            @endforeach

            <tr>
                <td class="text-right" colspan="4"><b>رسوم الشحن</b></td>
                <td class="text-right"> K.D {{$order->shipping}}</td>
            </tr>

            @if (!is_null($order->coupon))
                <tr>
                    <td class="text-right" colspan="4"><b>خصم الكوبون</b></td>
                    <td class="text-right"> K.D {{number_format($order->coupon_price,2)}}</td>
                </tr>

            @endif
            <tr>
                <td class="text-right" colspan="4"><b>المجموع</b></td>
                <td class="text-right"> K.D {{number_format($order->total,2)}}</td>
            </tr>
            </tbody>
        </table>

    </div>
    @endforeach

</div>


</body>

</html>

resources/views/page.blade.php
@extends('layouts.main')

@section('content')
    <div class="m-4 p-4">
        <div class="container">
            <div class="products_header d-flex justify-content-center align-items-center">
                <h2 class="text-center">{{$page->translate()->title}}</h2>
            </div>

            <div class="row" style="min-height: 60vh">
                <div class="container">
                    {!! $page->translate()->content !!}
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/product.blade.php
@extends('layouts.main')

@section('content')

    <div class="content-main container product-detail  ">
        <div class="row">





            <div id="content" class="product-view col-md-9 col-sm-12 col-xs-12 fluid-sidebar">




                <div class="content-product-mainheader clearfix">
                    <div class="row">
                        <div class="content-product-left  col-md-5 col-sm-12 col-xs-12">
                            <div class="so-loadeding"></div>

                            <div class="large-image  ">
                                <img itemprop="image" class="product-image-zoom lazyload" data-sizes="auto"
                                     src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                                     data-src="http://placehold.it/500/500"

                                     title="جل بذرة الكتان" alt="جل بذرة الكتان" />
                            </div>

                            <div id="thumb-slider" class="full_slider  contentslider" data-rtl="yes"
                                 data-autoplay="no" data-pagination="no" data-delay="4" data-speed="0.6"
                                 data-margin="10" data-items_column0="4" data-items_column1="3"
                                 data-items_column2="5" data-items_column3="3" data-items_column4="2"
                                 data-arrows="yes" data-lazyload="yes" data-loop="no" data-hoverpause="yes">


                            </div>



                        </div>

                        <div class="content-product-right col-md-7 col-sm-12 col-xs-12">
                            <div class="title-product">
                                <h1 style="font-size: 24px;">جل بذرة الكتان</h1>
                            </div>


                            <div class="product_page_price price" style="color:black!important;"
                                 itemprop="offerDetails" itemscope itemtype="http://data-vocabulary.org/Offer">
									<span class="price-new" style="color:black!important;"><span itemprop="price"
                                                                                                 id="price-old"> K.D 4.00</span></span>



                            </div>








                            <div id="product">

                                <div class="box-cart clearfix form-group">

                                    <div class="form-group box-info-product">
                                        <div class="option quantity">
                                            <label class="control-label" for="input-quantity">الكمية:</label>
                                            <div class="input-group quantity-control">
													<span
                                                        class="input-group-addon product_quantity_down fa fa-minus"></span>
                                                <input class="form-control" type="text" name="quantity" value="1" />
                                                <input type="hidden" name="product_id" value="50" />
                                                <span
                                                    class="input-group-addon product_quantity_up fa fa-plus"></span>
                                            </div>
                                        </div>
                                        <div class="detail-action">
                                            <div class="cart">
                                                <div class="form-group">
                                                    <input type="button" style="background-color: gray; "
                                                           value="إضافة إلى الحقيبة"
                                                           data-loading-text="جاري التحميل ..." id="button-cart"
                                                           class="btn btn-mega " />
                                                </div>
                                                <div class="form-group">
                                                    <input type="button"
                                                           style="background-color:#c8a9c8!important;margin: 0;"
                                                           value="الشراء الأن" data-loading-text="جاري التحميل ..."
                                                           id="button-checkout" class="btn btn-checkout btn-mega " />
                                                </div>



                                            </div>

                                        </div>
                                    </div>

                                    <div class="clearfix"></div>
                                </div>



                            </div>

                        </div>
                    </div>
                </div>

                <div class="content-product-mainbody clearfix row">


                    <div class="content-product-content col-sm-12">
                        <div class="content-product-midde clearfix">

                            <div class="producttab ">
                                <div class="tabsslider   horizontal-tabs  col-xs-12">


                                    <div class="tab-content  col-xs-12">
                                        <div class="tab-pane active" id="tab-description">


                                            <h3 class="product-property-title"> وصف المنتج</h3>
                                            <div id="collapse-description" class="desc-collapse showup">

                                            </div>

                                        </div>






                                    </div>
                                </div>
                            </div>
                        </div>



                    </div>

                </div>


            </div>
        </div>



    </div>
@endsection

resources/views/redirect.blade.php
<script>
    window.location.href = "{{$url}}"
</script>

resources/views/success.blade.php
@extends('layouts.main')

@section('content')
    <div class="row" style="padding-bottom: 20%;min-height: 80vh" >
        <div class="container">
            <div class="card">
                <div class="card-header">
                    <h2>{{trans('site.order_success')}}</h2>
                </div>

                <div class="card-body">
                    {!!  trans('site.order_success_message',['order_id'=>session()->get('order_id')])!!}
                </div>
            </div>
        </div>

    </div>


@endsection